apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.name }}
  dnsNames:
  - {{ .Values.certificate.dnsName }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.certificate.dnsName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: ClusterIssuer
